name: Node

on:
  pull_request:
    branches: [main]

env:
  # renovate: datasource=node
  NODE_VERSION: "21.2.0"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also emits such aliases as lts, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: "${{ env.NODE_VERSION }}"
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          # Package manager should be pre-installed
          # Default: ''
          cache: "npm"
      - run: npm ci
      - run: npx prettier . --check
